name: Update map
on: 
  push:
    branches: ['master']
    paths: ['agencies.json', 'process.js', 'fetch.mjs']
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # install action dependencies
    - uses: actions/setup-node@v3.5.1
    - uses: actions/checkout@v3
    
    # install npm dependencies
    - name: Install dependencies
      run: |
        npm install csv-parse
        npm install unzipper
        npm install node-fetch
        
    # fetch gtfs
    - name: fetch gtfs files
      run: |
        node fetch.mjs

    # process gtfs 
    - name: convert gtfs to geojson
      run: |
        node process.js
    # config git
    - name: config
      run: |
        git config --local user.name  ${{ github.actor }}
        git config --local user.email "72111431+aquaticpotato3677@users.noreply.github.com"
        
    # push data.json to master
    - name: stage changed files
      run: git add data.json
    - name: commit changed files
      run: git commit -m "updating data.json"
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
  deploy-to-pages:
    needs: build
    uses: ./.github/workflows/static.yml
